projectVersion=9.0.0-SNAPSHOT

grailsVersion=7.0.0-SNAPSHOT
javaVersion=17

asciidoctorGradleVersion=4.0.4
commonsValidatorVersion=1.9.0
hibernateVersion=5.6.15.Final
jakartaElVersion=4.0.0
jakartaElGlassfishImplVersion=4.0.2
javassistVersion=3.30.2-GA

# we use test containers to spin up mongodb for integration & functional example apps, the mongodbContainerVersion is
# the image to use from https://github.com/docker-library/docs/blob/master/mongo/README.md#supported-tags-and-respective-dockerfile-links
testcontainersMongoDbVersion=1.20.1
mongodbContainerVersion=7.0.16

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1536M -XX:MaxMetaspaceSize=512M