plugins {
    id 'com.gradle.develocity' version '3.19.1'
    id 'com.gradle.common-custom-user-data-gradle-plugin' version '2.1'
}

def isCI = System.getenv('CI') != null
def isLocal = !isCI
def isAuthenticated = System.getenv('DEVELOCITY_ACCESS_KEY') != null

develocity {
    server = 'https://ge.grails.org'
    buildScan {
        tag('grails')
        tag('grails-data-mapping')
        publishing.onlyIf { isAuthenticated }
        uploadInBackground = isLocal
    }
}

buildCache {
    local { enabled = isLocal }
    remote(develocity.buildCache) {
        push = isCI && isAuthenticated
        enabled = true
    }
}

rootProject.name = 'grails-data-mapping'

// grails-data-mapping
include(
    'grails-datastore-core',
    'grails-datastore-web',

    // Core GORM Implementation projects
    'grails-datastore-gorm',
    'grails-datastore-async',
    'grails-datastore-gorm-async',
    'grails-datastore-gorm-validation',
    'grails-datastore-gorm-support',
    'grails-datastore-gorm-tck',
    'grails-datastore-gorm-test',

    // RX projects
    // until this can be finished ported to grails 7, we are disabling
    //'grails-datastore-gorm-rx',

    // Testing Support
    'grails-gorm-testing-support',

    // Test Report
    'test-report'
)

// grails-data-mapping documentation
include 'docs-guide-developer'
project(':docs-guide-developer').projectDir = file('docs/guide-developer')

// until this can be finished ported to grails 7, we are disabling
//include 'docs-guide-rx'
//project(':docs-guide-rx').projectDir = file('docs/guide-rx')

include 'docs-guide-whats-new'
project(':docs-guide-whats-new').projectDir = file('docs/guide-whats-new')

// mongo documentation
include 'docs-gorm-mongodb'
project(':docs-gorm-mongodb').projectDir = file('docs/gorm-mongodb')

// mongo gorm 
include 'gorm-mongodb-grails-datastore-gorm-bson'
project(':gorm-mongodb-grails-datastore-gorm-bson').projectDir = file('gorm/mongodb/grails-datastore-gorm-bson')
include 'gorm-mongodb-grails-datastore-gorm-mongodb'
project(':gorm-mongodb-grails-datastore-gorm-mongodb').projectDir = file('gorm/mongodb/grails-datastore-gorm-mongodb')
include 'gorm-mongodb-grails-datastore-gorm-mongodb-ext'
project(':gorm-mongodb-grails-datastore-gorm-mongodb-ext').projectDir = file('gorm/mongodb/grails-datastore-gorm-mongodb-ext')

include 'gorm-mongodb-boot-plugin'
project(':gorm-mongodb-boot-plugin').projectDir = file('gorm/mongodb/boot-plugin')

include 'gorm-mongodb-grails-plugin'
project(':gorm-mongodb-grails-plugin').projectDir = file('gorm/mongodb/grails-plugin')

include 'gorm-mongodb-json-templates'
project(':gorm-mongodb-json-templates').projectDir = file('gorm/mongodb/json-templates')

// mongo gorm examples
include 'gorm-mongodb-examples-grails3-mongodb'
project(':gorm-mongodb-examples-grails3-mongodb').projectDir = new File(settingsDir, 'gorm/mongodb/examples/grails3-mongodb')

include 'gorm-mongodb-examples-grails3-mongodb-database-per-tenant'
project(':gorm-mongodb-examples-grails3-mongodb-database-per-tenant').projectDir = new File(settingsDir, 'gorm/mongodb/examples/grails3-mongodb-database-per-tenant')

include 'gorm-mongodb-examples-grails3-hibernate5-mongodb'
project(':gorm-mongodb-examples-grails3-hibernate5-mongodb').projectDir = new File(settingsDir, 'gorm/mongodb/examples/grails3-hibernate5-mongodb')

include 'gorm-mongodb-examples-springboot-mongodb'
project(':gorm-mongodb-examples-springboot-mongodb').projectDir = new File(settingsDir, 'gorm/mongodb/examples/springboot-mongodb')

include 'gorm-mongodb-examples-test-data-service'
project(':gorm-mongodb-examples-test-data-service').projectDir = new File(settingsDir, 'gorm/mongodb/examples/test-data-service')

include 'gorm-mongodb-examples-gson-templates'
project(':gorm-mongodb-examples-gson-templates').projectDir = new File(settingsDir, 'gorm/mongodb/examples/gson-templates')