plugins {
    id 'groovy'
    id 'org.springframework.boot'
}

group = 'example'

apply plugin: 'org.springframework.boot'

dependencies {
    implementation platform("org.grails:grails-bom:$grailsVersion")

    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.mongodb:mongodb-driver-sync"
    implementation project(":gorm-mongodb-boot-plugin")
    
    // For the example app, run an in memory db
    implementation "org.testcontainers:mongodb:$testcontainersMongoDbVersion"

    testImplementation "io.micrometer:micrometer-core:latest.integration"
    testImplementation "org.apache.groovy:groovy-test-junit5"
    testImplementation "org.hibernate.validator:hibernate-validator"
    testImplementation "org.spockframework:spock-core", { transitive = false }
    testImplementation "org.junit.jupiter:junit-jupiter-api"
    testImplementation "org.junit.platform:junit-platform-runner"
    testImplementation"org.springframework.boot:spring-boot-starter-test"
}

bootRun {
    System.setProperty('mongodbContainerVersion', mongodbContainerVersion)
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

apply from: rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
apply from: rootProject.layout.projectDirectory.file('gradle/test-config.gradle')