plugins {
    id 'groovy'
    id 'java-library'
}

version = projectVersion
group = 'org.grails'

ext {
    mavenPublishUrl = "https://repo.grails.org/grails/libs-snapshots-local"
}

dependencies {

    implementation platform("org.grails:grails-bom:$grailsVersion")

    api project(':grails-datastore-core'), {
        // api: MappingContext, PersistentProperty
        // impl: ClassPropertyFetcher, ClassUtils, PersistentEntity, GormProperties, Property, KeyValueMappingContext,
        //       PersistentEntity, GormProperties, Identity, ToOne
        if (excludeUnusedTransDeps) {
            // API dependencies in grails-datastore-core
            //exclude group: 'jakarta.persistence', module: 'jakarta.persistence-api' // FetchType
            //exclude group: 'org.javassist', module: 'javassist' // MethodHandler (in tests)
            exclude group: 'org.springframework', module: 'spring-context'
            exclude group: 'org.springframework', module: 'spring-core'
            exclude group: 'org.springframework', module: 'spring-tx'
        }
    }

    api "commons-validator:commons-validator:$commonsValidatorVersion", { // Candidate for grails-bom?
        exclude group: 'xml-apis', module:'xml-apis'
        exclude group: 'commons-digester', module:'commons-digester'
        exclude group: 'commons-logging', module:'commons-logging'
        exclude group: 'commons-beanutils', module:'commons-beanutils'
    }
    api 'org.springframework:spring-context'
    // api: Errors, MessageSource, Validator
    // impl: BindingResult, FieldError, LocaleContextHolder

    implementation 'org.slf4j:jcl-over-slf4j'
    // impl: Log, LogFactory

    implementation 'org.springframework:spring-beans'
    // impl: BeanWrapper, BeanWrapperImpl, InvalidPropertyException

    implementation 'org.springframework:spring-core'
    // impl: ReflectionUtils, ToStringCreator, Assert, StringUtils

    compileOnly 'org.apache.groovy:groovy'
    compileOnly 'org.slf4j:slf4j-api' // provided
    // impl: Logger, LoggerFactory

    testImplementation 'org.spockframework:spock-core'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly 'org.slf4j:slf4j-nop' // Get rid of warning about missing slf4j implementation during tests
}

apply from: rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
apply from: rootProject.layout.projectDirectory.file('gradle/test-config.gradle')
apply from: rootProject.layout.projectDirectory.file('gradle/publish-config.gradle')
