apply plugin: 'groovy'

configurations.register('documentation')

dependencies {
    documentation platform("org.grails:grails-bom:$grailsVersion")
    documentation 'org.apache.groovy:groovy-groovydoc'
    documentation 'org.apache.groovy:groovy-ant'
}

tasks.register('cleanDocs', Delete) {
    group = 'documentation'
    delete(rootProject.layout.buildDirectory.dir('docs'))
}

// grails-data-mapping api
tasks.register('data-mapping-groovydoc', Groovydoc) {
    group = 'documentation'
    description = 'Copies Groovy API Documentation for all supporting grails-data-mapping projects'
    Set<Project> docProjects = rootProject.subprojects.findAll {
        it.name in [
                'grails-datastore-async',
                'grails-datastore-core',
                'grails-datastore-gorm',
                'grails-datastore-gorm-async',
                'grails-datastore-gorm-support',
                'grails-datastore-gorm-validation',
                'grails-datastore-web',

                // These are test api docs that aren't typically included in the runtime classpath of applications.
                // for now include them in the groovy doc unless we want to call out that documentation separately later.
                'grails-datastore-gorm-test',
                'grails-gorm-testing-support'
        ]
    }

    for (Project docProject : docProjects) {
        docProject.sourceSets.main.allSource.srcDirs.each { File srcDir -> if(srcDir.exists()) inputs.dir(srcDir) }
    }

    docTitle = "Grails Data Mapping API - ${projectVersion}"
    source = docProjects.collect { it.sourceSets.main.allSource }.flatten()
    classpath = files(configurations.documentation + docProjects.configurations.compileClasspath)

    access = GroovydocAccess.PROTECTED
    includeAuthor = true
    includeMainForScripts = false
    processScripts = false
    destinationDir = project.layout.buildDirectory.dir('docs/api').get().asFile

    dependsOn([':cleanDocs'] + docProjects.collect { "$it.name:classes" })

    outputs.dir(project.layout.buildDirectory.dir('docs/api').get().asFile)
    doLast {
        delete(rootProject.layout.buildDirectory.dir('tmp'))
    }
}

// gorm api
tasks.register('gorm-groovydoc', Groovydoc) {
    group = 'documentation'
    description = 'Copies Groovy API Documentation for all supporting gorm implementation projects'
    Set<Project> docProjects = rootProject.subprojects.findAll {
        it.name in [
            'gorm-mongodb-boot-plugin',
            'gorm-mongodb-grails-datastore-gorm-bson',
            'gorm-mongodb-grails-datastore-gorm-mongodb',
            'gorm-mongodb-grails-datastore-gorm-mongodb-ext',
            'gorm-mongodb-grails-plugin'
            // gorm-mongodb-json-templates does not have any groovydoc
        ]
    }

    for (Project docProject : docProjects) {
        docProject.sourceSets.main.allSource.srcDirs.each { File srcDir -> if(srcDir.exists()) inputs.dir(srcDir) }
    }

    docTitle = "GORM for ${project.name.substring('gorm-'.length())} - ${projectVersion}"
    source = docProjects.collect { it.sourceSets.main.allSource }.flatten()
    classpath = files(configurations.documentation + docProjects.configurations.compileClasspath)

    access = GroovydocAccess.PROTECTED
    includeAuthor = true
    includeMainForScripts = false
    processScripts = false

    String targetApiDir = "docs/${project.name.substring('gorm-'.length())}/api"
    destinationDir = project.layout.buildDirectory.dir(targetApiDir).get().asFile

    //TODO: we should add `links` so the gorm API is linked in the mongo docs

    dependsOn([':cleanDocs'] + docProjects.collect { "$it.name:classes" })

    outputs.dir(project.layout.buildDirectory.dir(targetApiDir).get().asFile)
    doLast {
        delete(rootProject.layout.buildDirectory.dir('tmp'))
    }
}

tasks.register('docs') {
    group = 'documentation'
    dependsOn(':data-mapping-groovydoc', ':gorm-groovydoc')
    finalizedBy('copyRootWebsite','copyGuides')
}

tasks.register('copyRootWebsite', Copy) {
    group = 'documentation'
    from rootProject.layout.projectDirectory.dir('docs/data-mapping-website/src/main/resources')
    into rootProject.layout.buildDirectory.dir('docs')
}

tasks.register('copyGuides', Copy) {
    group = 'documentation'

    // guides
    for (Project subproject : subprojects.findAll { it.name.startsWith('docs-guide-') }) {
        dependsOn(subproject.tasks.named('asciidoctor'))
        def guideDirectory = subproject.layout.buildDirectory.dir('docs')
        from(guideDirectory) {
            includeEmptyDirs = false
            into ("${subproject.name.substring('docs-guide-'.length())}/manual")
        }
    }

    // gorm implementations
    for (Project subproject : subprojects.findAll { it.name.startsWith('docs-gorm-') }) {
        dependsOn(subproject.tasks.named('asciidoctor'))
        def guideDirectory = subproject.layout.buildDirectory.dir('docs')
        from(guideDirectory) {
            includeEmptyDirs = false
            into (subproject.name.substring('docs-gorm-'.length()))
        }
    }

    into rootProject.layout.buildDirectory.dir('docs')
}
