plugins {
    id 'groovy'
    id 'java-library'
}

version = projectVersion
group = 'org.grails'

ext {
    mavenPublishUrl = "https://repo.grails.org/grails/libs-snapshots-local"
}

dependencies {
    implementation platform("org.grails:grails-bom:$grailsVersion")

    api project(':grails-datastore-core'), {
        // api: Datastore
        // impl: DatastoreUtils, Session, SessionHolder
        if (excludeUnusedTransDeps) {
            // API dependencies in grails-datastore-core
            exclude group: 'jakarta.persistence', module: 'jakarta.persistence-api'
            exclude group: 'org.javassist', module: 'javassist'
            exclude group: 'org.springframework', module: 'spring-context'
            exclude group: 'org.springframework', module: 'spring-core'
            // exclude group: 'org.springframework', module: 'spring-tx' // ResourceHolderSupport
        }
    }
    api 'org.springframework:spring-context', {
        // api: ModelMap
    }
    api 'org.springframework:spring-web', {
        // api: WebRequest, WebRequestInterceptor
    }
    implementation 'org.springframework:spring-tx', {
        // impl: TransactionSynchronizationManager
    }

    compileOnlyApi 'jakarta.persistence:jakarta.persistence-api', {
        // compApi: FlushModeType
    }

    compileOnly 'jakarta.servlet:jakarta.servlet-api', {
        // comp: Cookie, HttpServletRequest
    }
    compileOnly 'org.apache.groovy:groovy', {
        // comp: CompileStatic
    }

    testImplementation 'jakarta.servlet:jakarta.servlet-api', {
        // impl: Cookie
    }
    testImplementation 'org.springframework:spring-test', {
        // impl: MockHttpServletRequest
    }
    testImplementation 'org.spockframework:spock-core'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly 'org.slf4j:slf4j-nop' // Get rid of warning about missing slf4j implementation during tests
}

apply from: rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
apply from: rootProject.layout.projectDirectory.file('gradle/test-config.gradle')
apply from: rootProject.layout.projectDirectory.file('gradle/publish-config.gradle')
