plugins {
    id 'groovy-gradle-plugin'
}

def versions = new Properties()
file('../gradle.properties').withInputStream {
    versions.load(it)
}

repositories {
    // mavenLocal()
    gradlePluginPortal()
    maven { url = 'https://repo.grails.org/grails/core' }
    mavenCentral()
    if (System.getenv('GITHUB_MAVEN_PASSWORD')) {
        maven {
            url = 'https://maven.pkg.github.com/grails/grails-core'
            credentials {
                username = 'DOES_NOT_MATTER'
                password = System.getenv('GITHUB_MAVEN_PASSWORD')
            }
        }
    }
}

dependencies {
    implementation platform("org.grails:grails-bom:${versions.getProperty('grailsVersion')}")
    implementation 'org.grails:grails-gradle-plugin'
    implementation 'com.bertramlabs.plugins:asset-pipeline-gradle'
    implementation 'org.grails.plugins:views-gradle'
}