plugins {
    id 'groovy'
    id 'java-library'
}

version = projectVersion
group = 'org.grails'

ext {
    pomArtifactId = 'grails-datastore-gorm-mongodb-bson'
    pomTitle = 'GORM for MongoDB'
    pomDescription = 'Provides a GORM Object Mapping implementations for the MongoDB Document Database'
    pomDevelopers = ['graemerocher': 'Graeme Rocher', 'jeffscottbrown': 'Jeff Brown', 'burtbeckwith': 'Burth Beckwith']
    mavenPublishUrl = 'https://repo.grails.org/grails/libs-snapshots-local'
}

dependencies {
    api "org.apache.groovy:groovy"
    api "org.apache.groovy:groovy-templates"
    api 'org.mongodb:bson'
    api project(':grails-datastore-gorm')

    implementation platform("org.grails:grails-bom:$grailsVersion")

    testImplementation "org.apache.groovy:groovy-json"
    testImplementation "org.apache.groovy:groovy-templates"
    testImplementation "org.apache.groovy:groovy-test-junit5"
    testImplementation "org.junit.jupiter:junit-jupiter-api"
    testImplementation "org.junit.platform:junit-platform-runner"
    testImplementation "org.spockframework:spock-core"
    testImplementation "org.testcontainers:mongodb"
}

apply from: rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
apply from: rootProject.layout.projectDirectory.file('gradle/test-config.gradle')
apply from: rootProject.layout.projectDirectory.file('gradle/publish-config.gradle')
