import org.asciidoctor.gradle.jvm.AsciidoctorTask

plugins {
    id 'org.asciidoctor.jvm.convert' version "${asciidoctorGradleVersion}"
}

version project.projectVersion
group 'org.grails'

def asciidoctorAttributes = [
        icons               : 'font',
        version             : project.version,
        imagesdir           : 'images',
]

tasks.named('asciidoctor', AsciidoctorTask) { AsciidoctorTask it ->
    inputs.dir project.layout.projectDirectory.dir('src/main/docs')
    outputs.dir project.layout.buildDirectory.dir('docs')

    it.jvm {
        jvmArgs("--add-opens", "java.base/sun.nio.ch=ALL-UNNAMED", "--add-opens", "java.base/java.io=ALL-UNNAMED")
    }
    it.baseDirFollowsSourceFile()
    it.sourceDir project.layout.projectDirectory.dir('src/main/docs')
    it.outputDir = project.layout.buildDirectory.dir('docs')
    it.attributes asciidoctorAttributes
}
